# Minimal Makefile for your specific build
# Compiles ../src/main.cpp using Eigen3 and outputs ../build/main.exe

all: ../build/main.exe

ex_0: ../src/ex_0.cpp
	/usr/bin/g++ ../src/ex_0.cpp -I /usr/include/eigen3 -o ../build/ex_0.exe

