# Minimal Makefile for your specific build
# Compiles ../src/main.cpp using Eigen3 and outputs ../build/main.exe

all: ../build/main.exe

../build/main.exe: ../src/main.cpp
	/usr/bin/g++ ../src/main.cpp -I /usr/include/eigen3 -o ../build/main.exe

